M.Page.AllOrderAction=M.createClass();M.extend(M.Page.AllOrderAction.prototype,{context:{},object:{},orderdata:{},ordertpl_first:'<tr class="${orderclass}" orderstatus="${orderstatuscode}" checkindate="${checkindate}" n="${nights}" rid="${roomid}" orderid="${id}" orderuniqid="${orderuniqid}">'
+'<td rowspan="${orderlength}">${createdate}</td>'
+'<td rowspan="${orderlength}">${guestname}</td>'
+'<td rowspan="${orderlength}">${channelname}</td>'
+'<td rowspan="${orderlength}"></td>'
+'<td class="tr">&yen;${totalprice}</td>'
+'<td>${orderstatusmsg}</td>'
+'<td>${roomname}</td>'
+'<td>${roomdate}</td>'
+'<td>${remark}</td>'
+'<td class="tc" ><a href="#?" tag="editorder" class="">查看订单</a></td>'
+'</tr>',ordertpl:'<tr class="${orderclass}" orderstatus="${orderstatuscode}" checkindate="${checkindate}" n="${nights}" rid="${roomid}" orderid="${id}" orderuniqid="${orderuniqid}">'
+'<td rowspan="${orderlength}" style="display:none">${createdate}</td>'
+'<td rowspan="${orderlength}" style="display:none">${guestname}</td>'
+'<td rowspan="${orderlength}" style="display:none">${channelname}</td>'
+'<td rowspan="${orderlength}"></td>'
+'<td class="tr">&yen;${totalprice}</td>'
+'<td>${orderstatusmsg}</td>'
+'<td>${roomname}</td>'
+'<td>${roomdate}</td>'
+'<td>${remark}</td>'
+'<td class="tc" ><a href="#?" tag="editorder" class="">查看订单</a></td>'
+'</tr>',init:function(arg){this.initDOM();this.initEvent();this.initordercallback();this.initdroplist();},initDOM:function(){this.context.document=$("body");this.context.orderlist=$("#orderlist");this.context.orderquery=$("#order_query");this.context.dateval=$("#dateval");this.context.datevallist=$("#datevallist");this.context.fromdate=$("#fromdate");this.context.enddate=$("#enddate");this.context.reloadbtn=$("#reloadbtn");this.context.pagelist=$("#pagelist");this.context.innlist=$("#innlist");this.context.fromdate.datepicker({onSelect:this.onselect_fromdate.toEventHandler(this)});this.context.enddate.datepicker({onSelect:this.onselect_enddate.toEventHandler(this)});this.context.allchannel=$("#allchannel");this.context.allroom=$("#allroom");this.context.allstatus=$("#allstatus");this.context.exportOrders=$("#exportOrders");},initEvent:function(){this.context.document.bind("click",this.document_click.toEventHandler(this));this.context.orderlist.bind("click",this.orderlist_click.toEventHandler(this));this.context.pagelist.bind("click",this.pagelist_click.toEventHandler(this));this.context.orderquery.bind("click",this.orderquery_click.toEventHandler(this));this.context.exportOrders.bind("click",this.exportorders_click.toEventHandler(this));this.context.orderlist.find('span[tag=remark]').each(function(){var text=$(this).text();$(this).attr("title",'').tooltip({position:{my:"left+15 top+20",at:"left bottom"},track:1,content:text,show:{duration:100}});});M.DropdownList(this.context.allchannel,this._submit_fun.toEventHandler(this),{});M.DropdownList(this.context.allroom,this._submit_fun.toEventHandler(this),{});M.DropdownList(this.context.allstatus,this._submit_fun.toEventHandler(this),{});},initordercallback:function(){order.ordercallback=this.editorder_finished.toEventHandler(this);order.checkincallback=this.editorder_finished.toEventHandler(this);var innid=this.context.orderquery.attr("innid");order.innid=innid;order.inituserauth();this.object.order=order;},onselect_fromdate:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");var fromdate=this.context.fromdate.val();var enddate=this.context.enddate.val();this.stop_enddate(fromdate,enddate);},stop_enddate:function(fromdate,enddate){var fromtime=M.strtotime(fromdate);var max_time=new Date(fromtime.getFullYear(),fromtime.getMonth()+2,fromtime.getDate());var max_date=M.timeformat(max_time);if(fromdate>enddate&&max_date<enddate){this.context.enddate.val(max_date);}
this.context.enddate.datepicker("option","minDate",fromdate);this.context.enddate.datepicker("option","maxDate",max_date);},onselect_enddate:function(e){},editorder_finished:function(d){if(d.status=="success"){window.location.reload();return;if(!M.isEmpty(d.action)&&d.action=="delete"){this._deleteorder(d);return;}
var orderlist=d.orderlist;if(M.isEmpty(orderlist)){orderlist=d.deleteddata;}
var orderunqid=d.orderunqid;this._showorderitem(orderunqid,orderlist);}},_showorderitem:function(orderunqid,orderlist){var targetlist=this.context.orderlist.find("tr[orderuniqid="+orderunqid+"]");var target=this.context.orderlist.find("tr[orderuniqid="+orderunqid+"]:last").next();targetlist.remove();var order_tpl_first=this.ordertpl_first;var order_tpl=this.ordertpl;orderlist=this._handleorderlist(orderlist);for(var i=0;i<orderlist.length;i++){var order=orderlist[i];order.orderlength=orderlist.length;if(i==0){var html=$.tmpl(order_tpl_first,order);}else{var html=$.tmpl(order_tpl,order);}
if(target.length==0){this.context.orderlist.children().append(html);}else{target.before(html);}}},_deleteorder:function(d){var orderlist=d.orderset.orders;var orderunqid=d.orderunqid;this._showorderitem(orderunqid,orderlist);},_handleorderlist:function(orderlist){if(M.isEmpty(orderlist)){orderlist={};return orderlist;}
for(var i=0;i<orderlist.length;i++){var order=orderlist[i];var date=order.d;var enddate=order.enddate;var datetime=M.strtotime(date);var enddatetime=M.strtotime(enddate);var datestr=M.timeformat(datetime,'m/d')+' - '+M.timeformat(enddatetime,'m/d');order.roomdate=datestr;order.createdate=M.timeformat(M.strtotime(order.createon),'Y-m-d');if(M.isEmpty(order.phone)){order.phone='-';}
if(order.status==1){if(order.type=="ordered"){order.orderclass='';order.orderstatuscode='1';order.orderstatusmsg='已预订';}else if(order.type=="checkedin"){order.orderstatuscode='2';order.orderstatusmsg='已入住';}else{order.orderstatuscode='3';order.orderstatusmsg='已退房';}}else{if(order.type=="ordered"){order.orderstatuscode='4';}else{order.orderstatuscode='5';}
order.orderclass='light';order.orderstatusmsg='已删除';}
if(order.orderstatuscode!=1&&order.orderstatuscode!=4&&order.orderid!=0){var datetime=M.strtotime(order.createon);order.createdate=M.timeformat(datetime,'Y-m-d')}
if(order.createuser==0){order.createuser=2;}
order.createby=this.object.order.userlist[order.createuser].username;orderlist[i]=order;}
return orderlist;},checkinoption_finished:function(){},orderlist_click:function(e){var ele=M.EventEle(e);var t=ele.attr("tag");switch(t){case'editorder':this.editorder(ele);break;case'handleorder':this.handleorder(ele);break;}},handleorder:function(ele){var type=ele.attr('type');var otaorderid=ele.parents('tr').attr('otaorderid')
M._getjson("/Ota/handleOrder",{'opertype':type,'orderid':otaorderid},this.handleorder_finished.toEventHandler(this));},handleorder_finished:function(d){if(d.status=='success'){window.location.reload()}else{M.error(d.msg);}},editorder:function(ele){var target=ele.parents("tr");var orderstatus=target.attr("orderstatus");var n=target.attr("n");var setid=target.attr("setid");var checkindate=target.attr("checkindate");var rid=target.attr("rid");var orderid=target.attr("orderid")
var orderunqid=target.attr("orderuniqid");var data={"orderstatus":orderstatus,"setid":setid,"n":n,"checkindate":checkindate,"rid":rid,"orderunqid":orderunqid};switch(orderstatus){case'1':data.oid=orderid;this.orderdata=data;this.object.order.doeditorder(data);break;case'2':data.gid=orderid;this.orderdata=data;this.object.order.doeditcheckingroup(data);break;case'3':data.gid=orderid;this.orderdata=data;this.object.order.doeditcheckingroup(data);break;case'4':data.oid=orderid;this.orderdata=data;this.object.order.doeditdeleteorder(data);break;case'5':data.gid=orderid;this.orderdata=data;this.object.order.doeditdeletedcheckingroup(data);break;case'6':data.gid=orderid;this.orderdata=data;this.object.order.doeditzeronightscheckingroup(data);break;}},orderquery_click:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");if(tag=='submit'){this._submit_fun(0);}
if(tag=='value'||tag=='dropdownlist'){this.context.datevallist.hide();}},exportorders_click:function(){M._getjson('/Reportsource/checkExportDataAuth',{},this.exportorders_finished.toEventHandler(this))},exportorders_finished:function(d){if(d.status=='success'){var innid=M.getinnid();var datetype=this.context.orderquery.find('div[t=sorttype]').children('span').attr('value');var fromdate=this.context.fromdate.val();var enddate=this.context.enddate.val();var channel=this.context.orderquery.find('div[t=channel]').children('span').attr('value');var room=this.context.orderquery.find('div[t=room]').children('span').attr('value');var status=this.context.orderquery.find('div[t=status]').children('span').attr('value');var param='?innid='+innid+'&sorttype='+datetype+'&fromdate='+fromdate+'&enddate='+enddate+'&channel='+channel+'&room='+room+'&status='+status;window.location.href="/Order/orderexport"+param;}else{alert(d.msg);}},_submit_fun:function(p){var datetype=this.context.orderquery.find('div[t=sorttype]').children('span').attr('value');var fromdate=this.context.fromdate.val();var enddate=this.context.enddate.val();var channel=this.context.orderquery.find('div[t=channel]').children('span').attr('value');var room=this.context.orderquery.find('div[t=room]').children('span').attr('value');var status=this.context.orderquery.find('div[t=status]').children('span').attr('value');var param='?sorttype='+datetype+'&fromdate='+fromdate+'&enddate='+enddate+'&channel='+channel+'&room='+room+'&status='+status;if(M.math_isnumber(p)){param+='&p='+p;}
window.location.href="/Order/index"+param;},pagelist_click:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");var p=1;if(tag=='pageindex'){return false;}
if(tag=='pageprev'){p=ele.attr('p');if(p<1){return false;}}
if(tag=='pagenext'){var page_max=this.context.pagelist.attr('maxpage');p=ele.attr('p');if(M.isEmpty(p)||p>page_max){return false;}}
if(tag=='page'){p=ele.attr('p');}
this._submit_fun(p);},initdroplist:function(){var tpl_sorttype=this.context.orderquery.find("div[t='sorttype']").attr("value",urldata.sorttype);M.DropdownList(tpl_sorttype,this._submit_fun.toEventHandler(this),null);var tpl_channel=this.context.orderquery.find("div[t='channel']").attr("value",urldata.channel);M.DropdownList(tpl_channel,this._submit_fun.toEventHandler(this),null);var tpl_status=this.context.orderquery.find("div[t='status']").attr("value",urldata.status);M.DropdownList(tpl_status,this._submit_fun.toEventHandler(this),null);var tpl_innid=this.context.orderquery.find("div[t='innlist']").attr("value",urldata.innid);M.DropdownList(tpl_innid,this._submit_fun.toEventHandler(this),null);var tpl_room=this.context.orderquery.find("div[t='room']").attr("value",urldata.room);M.DropdownList(tpl_room,this._submit_fun.toEventHandler(this),null);},document_click:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");if(M.isEmpty(tag)||(tag!='dropdownlist'&&tag!='value')){this.context.orderquery.find(".ip-dropdown[type='dropdownlist']:visible").hide();var box=ele.parents('div[tag=dateval]');if(box.length==0){var tpl=ele.parents("div.ui-corner-all");if(tpl.length==0){this.context.datevallist.hide();}}}},search_click:function(e)
{document.forms[0].submit();},NoUndefined:function(str)
{return M.isEmpty(str)?"":str;},_closepopup:function()
{},destroy:function(){}});