M.Page.SettingPage=M.createClass();M.extend(M.Page.SettingPage.prototype,{context:{},initpage:null,sendstatus:0,levelinfo:'',ruletype:0,ruletypename:{'1':'消费金额','2':'入住次数'},tpl_level:' <li lid="${id}"><label>${levelname}</label><a href="javascript:;" title="修改" class="edit" tag="modify">设置</a></li>',init:function(){this.initDOM();this.initEvent();},initDOM:function(){this.context.levellist=$("#levellist");this.context.addLevelPop=$("#addLevelPop");this.ruletype=this.context.addLevelPop.attr("rt");},initEvent:function(){this.context.levellist.bind('click',this.levellist_click.toEventHandler(this));this.context.addLevelPop.bind('click',this.addLevelPop_click.toEventHandler(this));},levellist_click:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");switch(tag){case'add':this.inittpl_levelSetting('');break;case'modify':this.modifylevel(ele);break;}},modifylevel:function(ele){var data={'lid':ele.parent().attr('lid')};M._getjson("/Crm/getlevel",data,this._getlevel_finished.toEventHandler(this));},_getlevel_finished:function(d){if(d.status=='success'){this.inittpl_levelSetting(d.data);this.levelinfo=d.data;}else{alert(d.msg);}},inittpl_levelSetting:function(data){M.Popup(this.context.addLevelPop,{"hideclass":"modal view fade","showclass":"modal view fade in"});var html_ul=this.context.addLevelPop.find('ul');html_ul.find('input[name=rulevalue]').val('');html_ul.find('input[tag=discount]').next('input').val('');html_ul.find('input[tag=reduce]').next('input').val('');html_ul.find('input[tag=nodiscount]').attr('checked','checked');if(!M.isEmpty(data)){this.context.addLevelPop.attr('lid',data.id);this.context.addLevelPop.find('h3[tag=tit]').html('修改会员等级');html_ul.find('input[name=levelname]').val(data.levelname);html_ul.find('input[name=upgrade][value='+data.upgrade+']').attr('checked','checked');if(data.upgrade==1){this.context.addLevelPop.find('ul[tag=rule]').show();}else{html_ul.find('input[name=autoupgrade]').removeAttr('checked');html_ul.find('input[name=noautoupgrade]').attr('checked','checked');this.context.addLevelPop.find('ul[tag=rule]').hide();}
html_ul.find('li[tag=rulevalue]').show();if(!M.isEmpty(data.rulevalue)&&data.rulevalue!=0){html_ul.find('input[name=rulevalue]').val(data.rulevalue);}
if(data.ruletype!=0){html_ul.find("input[name=ruletype][value="+data.ruletype+"]").attr('checked','checked');this.context.addLevelPop.attr('ruletype',data.ruletype);html_ul.children("li[tag=rule]").html('您已选定按'+this.ruletypename[data.ruletype]+'作为自动升级规则：');html_ul.children("li[tag=rulelist]").hide();if(data.ruletype==1){html_ul.find('span[tag=ruletxt]').html('消费金额达到');html_ul.find('input[name=rulevalue]').attr("placeholder","金额")
html_ul.find('span[tag=unit]').html('元');}else if(data.ruletype==2){html_ul.find('span[tag=ruletxt]').html('入住次数达到');html_ul.find('span[tag=unit]').html('次');html_ul.find('input[name=rulevalue]').attr("placeholder","次数")}}else{html_ul.find('input[name=ruletype]').removeAttr('checked');html_ul.find('li[tag=rulevalue]').hide();}
html_ul.find('input[tag=reduce]').attr('checked',false);html_ul.find('input[tag=discount]').attr('checked',false);if(data.is_discount==1){html_ul.find('input[tag=discount]').attr('checked','checked');html_ul.find('input[tag=discount]').next('input').val(data.discount);}else if(data.is_discount==2){html_ul.find('input[tag=reduce]').attr('checked','checked');html_ul.find('input[tag=reduce]').next('input').val(data.reduce);}}else{this.context.addLevelPop.attr('lid',0);this.context.addLevelPop.find('h3[tag=tit]').html('添加会员等级');html_ul.find('input[name=levelname]').val('');html_ul.find('input[name=upgrade][value=0]').attr('checked','checked');html_ul.find('input[name=ruletype]').removeAttr('checked');html_ul.find('li[tag=rulevalue]').hide();if(this.ruletype!=0){html_ul.children("li[tag=rule]").html('您已选定按'+this.ruletypename[this.ruletype]+'作为自动升级规则：');if(this.ruletype==1){html_ul.find('span[tag=ruletxt]').html('消费金额达到');html_ul.find('input[name=rulevalue]').attr("placeholder","金额");html_ul.find('span[tag=unit]').html('元');html_ul.find("li[tag=rulevalue]").show();}else if(this.ruletype==2){html_ul.find('span[tag=ruletxt]').html('入住次数达到');html_ul.find('span[tag=unit]').html('次');html_ul.find('input[name=rulevalue]').attr("placeholder","次数");html_ul.find("li[tag=rulevalue]").show();}
html_ul.children("li[tag=rulelist]").hide();html_ul.children("li[tag=rulevalue]").show();}
this.context.addLevelPop.find('ul[tag=rule]').hide();html_ul.find('input[name=levelname]').select();}},savelevel:function(ele){var html_ul=this.context.addLevelPop.find('ul');var id=this.context.addLevelPop.attr('lid');var levelname=html_ul.find('input[name=levelname]').val();var upgrade=html_ul.find("input[name=upgrade]:checked").val();var ruletype=M.getVal(html_ul.find("input[name=ruletype]:checked"));var rulevalue=M.getVal(html_ul.find("input[name=rulevalue]"));var discounttype=html_ul.find("input[name=discount]:checked").attr('tag');if(M.isEmpty(levelname)){alert("等级名称不能为空");return;}else if(M.getstrlength(levelname)>16){alert("等级名称最多只能输入8个字");return;}
if(upgrade=='1'){if(M.isEmpty(ruletype)){ruletype=this.ruletype;}
if(M.isEmpty(ruletype)){alert("请选择自动升级规则");return;}
if(rulevalue===0){alert("请输入大于0的数值");return;}
if(ruletype=='1'&&M.isEmpty(rulevalue)){alert("消费金额不能为空");return;}
if(ruletype=='2'&&M.isEmpty(rulevalue)){alert("入住次数不能为空");return;}}
var discount=0;var reduce=0;if(discounttype=='discount'){discount=M.getVal(html_ul.find("input[tag=discount]").next('input'));if(0>discount||discount>=10){alert("请输入0-10之间折扣数字");return;}else if(!this._checknum(discount)){alert('折扣最多只支持1位小数喔');return;}}else if(discounttype=='reduce'){var reduce=M.getVal(html_ul.find("input[tag=reduce]").next('input'));if(M.isEmpty(reduce)){alert('请输入大于0的数字哦');return;}
if(!M.math_isnumber(reduce)){alert('立减金额只能为数字哦');return;}}
var sendstatus=this.context.addLevelPop.attr("sendstatus");if(sendstatus==1){return;}
this.context.addLevelPop.attr("sendstatus","1");var data={'id':id,'levelname':levelname,'upgrade':upgrade,'ruletype':ruletype,'rulevalue':rulevalue,'discounttype':discounttype,'discount':discount,'reduce':reduce};M._getjson("/Crm/settingsave",data,this.savelevel_finished.toEventHandler(this));},savelevel_finished:function(d){this.context.addLevelPop.attr("sendstatus","0");if(d.status=="success"){M.success("保存成功");M.ClosePopup();var data=d.data;var req_id=d.id;if(data.ruletype>0){this.ruletype=data.ruletype;}
if(!M.isEmpty(req_id)&&req_id!=0){this.context.levellist.find('ul').children('li[lid='+req_id+']').children('label').html(data.levelname);}else{var html=$.tmpl(this.tpl_level,data);this.context.levellist.find('ul').children("li[tag=add]").before(html);if(this.context.levellist.find('ul').children('li[tag!=add]').length>=8){this.context.levellist.find('ul').children('li[tag=add]').hide();}}}else{alert(d.msg);}},_checknum:function(num){var num_arr=num.toString().split(".");if(!M.isEmpty(num_arr[1])&&num_arr[1].length>1){return false;}else{return true;}},addLevelPop_click:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");if(M.isEmpty(tag)){tag=ele.attr("name");}
switch(tag){case'upgrade':this.tpl_autoupgrade(ele);break;case'settype':this.tpl_autoupgraderules(ele);break;case'save':this.savelevel(ele);break;}},tpl_autoupgrade:function(ele){var type=ele.val();if(type=='1'){this.context.addLevelPop.find('ul[tag=rule]').show();}else{this.context.addLevelPop.find('ul[tag=rule]').hide();}},tpl_autoupgraderules:function(ele,type){var value=ele.attr("value");var html_li=this.context.addLevelPop.find('ul[tag=rule]');html_li.children('li[tag=rulevalue]').show();if(value=='1'){html_li.find('span[tag=ruletxt]').html('消费金额达到');html_li.find('span[tag=unit]').html('元');html_li.find('input[name=rulevalue]').attr("placeholder","金额")}else{html_li.find('span[tag=ruletxt]').html('入住次数达到');html_li.find('span[tag=unit]').html('次');html_li.find('input[name=rulevalue]').attr("placeholder","次数")}},_closepopup:function()
{M.ClosePopup();},destroy:function(){}});var setting;M.ready(function(){setting=new M.Page.SettingPage();return setting;});