M.Page.GetPassWordPage=M.createClass();M.extend(M.Page.GetPassWordPage.prototype,{context:{},on_init:null,timer:null,codestr:'',init:function(){this.initDOM();this.initEvent();},initDOM:function(){this.context.resetpassform=$("#resetpassform");this.context.validform=$("#validform");this.context.cardno=$('#cardno');this.context.forgetcardno=$("#forgetcardno");this.context.phone=$("#phone");this.context.sendvalidcodebtn=$("#sendvalidcode");this.context.resendresendvalidcode=$("#resendvalidcode");this.context.validcode=$("#validcode");this.context.resetpassbtn=$("#resetpass");this.context.newpass=$("#newpass");this.context.confirmpass=$("#confirmpass");this.context.submitpass=$("#submitpass");this.context.valid=$("#valid");this.context.content=$("#content");},initEvent:function(){this.context.forgetcardno.bind('hover',this.forgetcardno_hover.toEventHandler(this));this.context.forgetcardno.bind('mouseout',this.forgetcardno_hoverout.toEventHandler(this));this.context.sendvalidcodebtn.bind('click',this.sndvalidcodebtn_click.toEventHandler(this));this.context.resetpassbtn.bind('click',this.resetpass_click.toEventHandler(this));this.context.submitpass.bind('click',this.submitpass_click.toEventHandler(this));this.context.content.find('input').bind('keydown',this.input_change.toEventHandler(this));},input_change:function(e){var ele=M.EventEle(e);var t=ele.attr('name');switch(t){case'phone':this.context.content.find('p[tag=phone_error]').hide();break;case'valid':this.context.content.find('p[tag=valid_error]').hide();break;case'validcode':this.context.content.find('p[tag=validcode_error]').hide();break;case'password':this.context.content.find('p[tag=password_error]').hide();break;case'confirmpass':this.context.content.find('p[tag=confirmpass_error]').hide();this.context.content.find('p[tag=password_error]').hide();break;}},forgetcardno_hover:function()
{this.context.forgetcardno.attr("class","forgetCard forgetCard_on ml20");},forgetcardno_hoverout:function()
{this.context.forgetcardno.attr("class","forgetCard ml20");},submitpass_click:function(){var newpass=this.context.newpass.val();var confirmpass=this.context.confirmpass.val();var phone=this.context.phone.val().trim();if(M.isEmpty(newpass))
{this.context.content.find('p[tag=password_error]').html('密码不能为空').show();return;}
if(newpass.length<6||newpass.length>20){this.context.content.find('p[tag=password_error]').html('密码长度只能为6~20位').show();return;}
if(M.isEmpty(confirmpass))
{this.context.content.find('p[tag=confirmpass_error]').html('确认密码不能为空').show();return;}
if(confirmpass!=newpass)
{this.context.content.find('p[tag=confirmpass_error]').html('两次输入的密码不一致').show();return;}
var data={"phone":phone,"newpass":newpass,"confirmpass":confirmpass,"vcode":this.codestr};M._getjson("/Password/resetPwd",data,this.submitpass_finished.toEventHandler(this));},submitpass_finished:function(d){if(d.status=='success'){M.success('重置密码成功');var _this=this;wx.miniProgram.getEnv(function(res){if(res.miniprogram===true){window.setTimeout(_this.backToMiniProgram,1500);return true;}});window.setTimeout(this.location_href,2000);}else{this.context.content.find('p[tag=confirmpass_error]').html(d.msg).show();}},backToMiniProgram:function(){wx.miniProgram.navigateBack({});},location_href:function(){window.location.href="/Login/index";},resetpass_click:function(){var phone=this.context.phone.val().trim();var vcode=this.context.validcode.val().trim();if(M.isEmpty(phone))
{this.context.content.find('p[tag=phone_error]').html('手机号不能为空').show();return;}
if(isNaN(phone)||phone.length!=11)
{this.context.content.find('p[tag=phone_error]').html('手机号格式不正确').show();return;}
if(M.isEmpty(vcode))
{this.context.content.find('p[tag=validcode_error]').html('短信验证码不能为空').show();return;}
var data={"phone":phone,"vcode":vcode};M._getjson("/Password/checkVcode",data,this.checkvcode_finished.toEventHandler(this));},checkvcode_finished:function(d){if(d.status=='success'){this.context.validform.hide();this.context.resetpassform.show();this.context.resetpassform.find("td[tag=username]").html(d.userid);this.codestr=d.d.code;}else{var error_type=d.error_type;if(error_type=='valid'){this.context.content.find('p[tag=validcode_error]').html(d.msg).show();}else{this.context.content.find('p[tag=phone_error]').html(d.msg).show();}}},sndvalidcodebtn_click:function(e)
{var phone=this.context.phone.val().trim();if(M.isEmpty(phone))
{this.context.content.find('p[tag=phone_error]').html('手机号不能为空').show();return;}
if(isNaN(phone)||phone.length!=11)
{this.context.content.find('p[tag=phone_error]').html('手机号格式不正确').show();return;}
var valid=this.context.valid.val();M._getjson("/Password/sendMsg",{"phone":phone,'valid':valid},this.sendvalidcode_finished.toEventHandler(this),'',true);},sendvalidcode_finished:function(d)
{if(d.status=='success')
{this.context.resetpassbtn.removeClass("btn-no").addClass("btn");this.context.sendvalidcodebtn.hide();this.context.resendresendvalidcode.show();this.timer=window.setInterval(this.run.toEventHandler(this),1000);}
else
{var error_type=d.error_type;if(error_type=='valid'){this.context.content.find('p[tag=valid_error]').html(d.msg).show();}else{this.context.content.find('p[tag=phone_error]').html(d.msg).show();}}},run:function(){var text=this.context.resendresendvalidcode.val();var num=parseInt(text);if(num==0){this.context.sendvalidcodebtn.val("重新发送");this.context.sendvalidcodebtn.show();this.context.resendresendvalidcode.hide();this.context.resendresendvalidcode.val('60秒后可重发');window.clearInterval(this.timer);}else{num=num-1;this.context.resendresendvalidcode.val(num+'秒后可重发');}},NoUndefined:function(str)
{return M.isEmpty(str)?"":str;},_closepopup:function()
{},destroy:function(){}});M.ready(function(){var forgetpwd=new M.Page.GetPassWordPage();return forgetpwd;});