M.Page.LoginPage=M.createClass();M.extend(M.Page.LoginPage.prototype,{context:{},on_init:null,init:function(arg){this.initDOM();this.initEvent();if(!M.isEmpty(this.on_init))
{this.on_init.call(this);}
this.context.username.focus();},initDOM:function(){this.context.username=$("#username");this.context.password=$("#password");this.context.innform=$("#innform");this.context.i_innname=$("#i_innname");this.context.i_phone=$("#i_phone");this.context.i_contact=$("#i_contact");this.context.i_cityname=$("#i_cityname");this.context.i_areaname=$("#i_areaname");this.context.i_manager=$("#i_manager");this.context.inn_overlay=$("#inn_overlay");this.context.loginform=$(document.forms[0]);this.context.cityList=$('#cityList');this.context.areaList=$('#areaList');this.context.countrybox=$("#countrybox");},initEvent:function(){this.context.loginform.bind("submit",this.loginform_submit.toEventHandler(this));this.context.innform.bind("click",this.innform_click.toEventHandler(this));this.context.i_innname.bind("focus",this.hide_click.toEventHandler(this));this.context.i_contact.bind("focus",this.hide_click.toEventHandler(this));this.context.i_manager.bind("focus",this.hide_click.toEventHandler(this));this.context.i_cityname.bind("focus",this.cityList.toEventHandler(this));this.context.cityList.bind("click",this.cityList_click.toEventHandler(this));this.context.areaList.bind("click",this.areaList_click.toEventHandler(this));this.context.countrybox.bind("click",this.countrybox_click.toEventHandler(this));},hide_click:function(e){this.context.cityList.hide();this.context.areaList.hide();},close_click:function(e)
{this._closepopup();},loginform_submit:function(element)
{var username=this.context.username.val();var password=this.context.password.val();if(M.isEmpty(username))
{this.context.username.focus();alert("请输入用户名");return false;}
if(M.isEmpty(password))
{this.context.password.focus();alert("请输入密码");return false;}
document.forms[0].submit();},innform_click:function(e)
{var ele=M.EventEle(e);var t=ele.attr("tag");switch(t){case'closebtn':this.context.cityList.hide();this.context.areaList.hide();this._closepopup();break;case'area':this.targetarea=ele;this.areaList(ele);break;case'add':this.addareatpl();break;case'del':this.delareatpl(ele);break;case'save':this.saveinninfo();break;case'inntype':ele.parent().children().removeClass('on');ele.addClass('on');break;case'country':this.country(ele);break;}},delareatpl:function(ele){var tpl=this.context.innform.find("li[tag=area_li]");if(tpl.length==2){ele.parents("li").remove();}
this._initareabtn();},addareatpl:function(){var tpl=this.context.innform.find("li[tag=area_li]");if(tpl.length==1){var target=tpl.clone().attr("t",'addtpl').attr("areaid","");target.children("input[name=area]").val('');tpl.after(target);}
this._initareabtn();},_initareabtn:function(){var tpllist=this.context.innform.find("li[tag=area_li]");if(tpllist.length==1){tpllist.children("a[t=op]").attr("title","添加区域").removeClass('del-book').addClass('add-book').attr("tag","add");}else{tpllist.children("a[t=op]").attr("title","添加区域").removeClass('add-book').addClass('del-book').attr("tag","del");}},countrybox_click:function(e){var ele=M.EventEle(e);var t=ele.attr('tag');if(t=='close'){this.context.countrybox.hide();return true;}else if(t!='country'){return true;}
var value=ele.attr('value');var name=ele.html();this.context.innform.find('li[tag=type]').children('input[tag=country]').val(name).attr('data-val',value);this.context.countrybox.hide();this.context.i_cityname.attr('cityid',0).attr('desid',0).val('');this.context.innform.find('li[tag=area_li]').children('input').attr('areaid',0).attr('cityid',0).attr('desid',0).val('');},country:function(ele){this.context.cityList.hide();this.context.areaList.hide();var left=ele.offset().left;var objtop=ele.offset().top+ele.outerHeight();this.context.countrybox.css("left",left).css("top",objtop).show();var html="";for(var k in country){var val=country[k];html+='<a tag="country" value="'+val.id+'" href="javascript:;">'+val.name+'</a>';}
this.context.countrybox.find('div[tag=list]').html(html);},initcitydata:function(countryid){var hothtml="";var hotdeslist=hotdes[countryid];if(!M.isEmpty(hotdeslist)){for(var key in hotdeslist){var hotdesinfo=hotdeslist[key];hothtml+="<a href='javascript:;' desid='"+hotdesinfo.id+"' cityid='"+hotdesinfo.p_id+"' tag='selecthot'>"+hotdesinfo.name+"</a>";}}else{hothtml='暂未添加热门，请选择“全部”';}
var dishtml="";if(M.isEmpty(district[countryid])){alert('获取数据失败');return;}
var provincelist=district[countryid];for(var key in provincelist){var provinceinfo=provincelist[key];dishtml+="<a href='javascript:;' cityid='"+provinceinfo.id+"' tag='selectdis'>"+provinceinfo.name+"</a>";}
this.context.cityList.find("li[tag=hot]").children("div").html(hothtml);this.context.cityList.find("li[tag=all]").find("div[tag=provincelist]").html(dishtml);},cityList:function(){this.context.countrybox.hide();var countryid=this.context.i_cityname.parent().children('input[tag=country]').attr('data-val');this.initcitydata(countryid);this.context.areaList.hide();var left=this.context.i_cityname.offset().left;var objtop=this.context.i_cityname.offset().top+this.context.i_cityname.outerHeight();this.context.cityList.css("left",left).css("top",objtop);this.context.cityList.find("li[tag=hot]").show();this.context.cityList.find("li[tag=all]").hide();this.context.cityList.find("a[tag=tabAll]").removeClass("on");this.context.cityList.find("a[tag=tabHot]").removeClass("").addClass("on");this.context.cityList.show();},areaList:function(ele){this.context.countrybox.hide();this.context.cityList.hide();var cityid=this.context.i_cityname.attr("cityid");var desid=this.context.i_cityname.attr("desid");if(M.isEmpty(cityid)&&M.isEmpty(desid)){return;}
var left=ele.offset().left;var objtop=ele.offset().top+ele.outerHeight();this.context.areaList.css("left",left).css("top",objtop);var areahtml="";var arealist=area[desid];if(!M.isEmpty(arealist)){for(var key in arealist){var areainfo=arealist[key];areahtml+="<a href='javascript:;' cityid='"+cityid+"' desid='"+desid+"' areaid='"+areainfo.id+"' tag='selectarea'>"+areainfo.name+"</a>";}}
if(!M.isEmpty(areahtml)){this.context.areaList.find("div[tag=arealist]").html(areahtml);this.context.areaList.show();}},cityList_click:function(e){var ele=M.EventEle(e);var t=ele.attr("tag");if(t=="closelist")
{this.context.cityList.hide();}
if(t=="tabHot"){this.context.cityList.find("li[tag=hot]").show();this.context.cityList.find("li[tag=all]").hide();this.context.cityList.find("a[tag=tabAll]").removeClass("on");this.context.cityList.find("a[tag=tabHot]").removeClass("").addClass("on");}
if(t=="tabAll"){this.context.cityList.find("li[tag=hot]").hide();this.context.cityList.find("li[tag=all]").show();this.context.cityList.find("div[tag=province]").show();this.context.cityList.find("div[tag=provincelist]").show();this.context.cityList.find("div[tag=hasProvince]").hide();this.context.cityList.find("a[tag=tabHot]").removeClass("on");this.context.cityList.find("a[tag=tabAll]").removeClass("").addClass("on");}
if(t=="selectdis")
{var cityid=ele.attr("cityid");var cityname=ele.text();var dishtml="";var deslist=des[cityid];if(!M.isEmpty(deslist)){for(var key in deslist){var desinfo=deslist[key];dishtml+="<a href='javascript:;' cityid='"+cityid+"' desid='"+desinfo.id+"' tag='selectdes'>"+desinfo.name+"</a>";}}else{dishtml+='数据加载出错，请联系客户经理';}
this.context.cityList.find("li[tag=all]").find("div[tag=province]").hide();this.context.cityList.find("li[tag=all]").find("div[tag=hasProvince]").show();this.context.cityList.find("li[tag=all]").find("strong[tag=disname]").text(cityname);this.context.cityList.find("li[tag=all]").find("div[tag=hasProvincelist]").html(dishtml);}
if(t=="editdis")
{this.context.cityList.find("li[tag=all]").find("div[tag=province]").show();this.context.cityList.find("li[tag=all]").find("div[tag=hasProvince]").hide();}
if(t=="selectdes")
{var cityid=ele.attr("cityid");var desid=ele.attr("desid");var desname=ele.text();var hasdesid=this.context.i_cityname.attr("desid");this.context.i_cityname.attr("cityid",cityid).attr("desid",desid).val(desname);if(hasdesid!=desid){this.context.innform.find("li[tag=area_li]").children("input").val("").attr("areaid","").attr("desid","");}
this.context.cityList.hide();this.checkareaexsit(cityid,desid);}
if(t=="selecthot")
{var cityid=ele.attr("cityid");var desid=ele.attr("desid");var hotdesname=ele.text();var hashotdesid=this.context.i_cityname.attr("desid");this.context.i_cityname.attr("cityid",cityid).attr("desid",desid).val(hotdesname);if(hashotdesid!=desid){this.context.innform.find("li[tag=area_li]").children("input").val("").attr("areaid","").attr("desid","");}
this.context.cityList.hide();this.checkareaexsit(cityid,desid);}},checkareaexsit:function(cityid,desid){var areahtml="";var arealist=area[desid];if(!M.isEmpty(arealist)){areahtml=1;}
if(!M.isEmpty(areahtml)){this.context.i_areaname.attr("hasarea",1);}else{this.context.i_areaname.attr("hasarea",0);}},areaList_click:function(e){var ele=M.EventEle(e);var t=ele.attr("tag");if(t=="closelist")
{this.context.areaList.hide();}
if(t=="selectarea")
{var areaid=ele.attr("areaid");var areaname=ele.text();var cityid=ele.attr("cityid");var desid=ele.attr("desid");this.targetarea.attr("areaid",areaid).attr("cityid",cityid).attr("desid",desid).val(areaname);this.context.areaList.hide();}},showinnform:function()
{M.Popup(this.context.innform,{"hideclass":"bootbox modal fade","showclass":"bootbox modal fade in"},function(){this.context.i_innname.focus();}.toEventHandler(this));},saveinninfo:function()
{var innname=M.getVal(this.context.i_innname);var phone=M.getVal(this.context.i_phone);var contact=M.getVal(this.context.i_contact);var cityname=M.getVal(this.context.i_cityname);var desid=this.context.i_cityname.attr("desid");var areaid=this.context.i_areaname.attr("areaid");var hasarea=this.context.i_areaname.attr("hasarea");var areaname=M.getVal(this.context.i_areaname);var managerphone=M.getVal(this.context.i_manager);var inntype=this.context.innform.find('li[tag=inntype_li]').find('a.on').attr('data-val');var countryid=this.context.innform.find('li[tag=type]').children('input[tag=country]').attr('data-val');var countryname=this.context.innform.find('li[tag=type]').children('input[tag=country]').val();var regu=/['"$<>]+/;var re=new RegExp(regu);if(re.test(innname)){alert("请不要客栈名中使用 \' \" $ < > 等特殊符号");return;}
var cardno=this.context.innform.attr("cardnum");var pwd=this.context.innform.attr("pwd");var data={"innname":innname,"phone":phone,"contact":contact,"cardno":cardno,"desid":desid,"pwd":pwd,'inntype':inntype,"cityname":cityname,"hasarea":hasarea,"areaid":areaid,"areaname":areaname,"manager":managerphone,'countryid':countryid,'countryname':countryname};if(hasarea==1){var tpl=this.context.innform.find("li[tag=area_li]");var i=0;tpl.each(function(){var areaid=$(this).children("input[name=area]").attr("areaid");if(!M.isEmpty(areaid)&&areaid!=0){data['areaid'+i]=areaid;data['areaname'+i]=$(this).children("input[name=area]").val();i++;}});if(M.isEmpty(data['areaid0'])){alert('区域不能为空');return;}
if(!M.isEmpty(data['areaid1'])){if(data['areaid1']==data['areaid0']){alert('区域不能相同');return;}}}
M._getjson("/Login/dosaveinfo",data,this.saveinninfo_finished.toEventHandler(this));},saveinninfo_finished:function(d)
{if(d.status=="success")
{alert('恭喜，您的客栈已经开通！现在开始维护你的房型吧!');window.top.location.href="/RoomType/index?t="+new Date().getMilliseconds();}
else
{if(!M.isEmpty(d.msg))
{alert(d.msg);}}},NoUndefined:function(str)
{return M.isEmpty(str)?"":str;},_closepopup:function()
{this.context.inn_overlay.hide();this.context.innform.hide();},destroy:function(){}});