M.Page.OtaOtherPage=M.createClass();M.extend(M.Page.OtaOtherPage.prototype,{context:{},otacode:'',ota_type:{'yzgdx':'云掌柜代销','elong':'艺龙','ctrip':'携程','qunarlink':'去哪儿','tujia':'途家','booking':'Booking','agoda':'Agoda','alitrip':'阿里信用住','airbnb':'Airbnb','xiaozhu':'小猪短租','weila':'维拉度假','msk':'民宿客','zhisu':'知宿','jsyx':'借宿严选','zhenguo':'榛果'},rules_title:{'yzgdx':'在线签约','elong':'关联艺龙注意事项','ctripbefore':'关联携程注意事项','ctrip':'关联携程注意事项','qunarlink':'关联去哪儿注意事项','tujia':'关联途家注意事项','booking':'Booking直连须知','agoda':'关联Agoda注意事项','meituan':'关联美团注意事项','alitrip':'关联阿里信用住注意事项','airbnb':'关联Airbnb注意事项','expedia':'关联Expedia注意事项','jihe':'几何民宿关联云掌柜注意事项','qmango':'青芒果关联云掌柜注意事项','xiaozhu':'小猪短租关联云掌柜注意事项','weila':'维拉度假关联云掌柜注意事项','msk':'民宿客关联云掌柜注意事项','zhisu':'知宿关联云掌柜注意事项','jsyx':'借宿严选关联云掌柜注意事项','zhenguo':'榛果关联云掌柜注意事项',},rules_content:{'yzgdx':'<h3 style="font-size:18px;margin-top:10px;">云掌柜代销合作协议</h3>'
+' <p class="t12 mt5 mb5">甲方:北京米天下科技股份有限公司</br>乙方:</p><p class="t12 mt5 mb5" style="border-top:1px solid #ccc;padding-top:10px;">甲乙双方经友好协商,就云掌柜代销合作达成一致,如下:</p><p class="t12 mt5 mb5 green">一、关键词解释</p><p class="t12 mt5 mb5">云掌柜代销:为了更有效地推销乙方客栈,乙方授权甲方可自主决定通过其自身或其他渠 道,包括但不限于航空、电信、银行、网站联盟、旅行社等多种销售渠道,以网络,电话等多种销售方式开展客房预订业务,销售乙方客房。由甲方帮助乙方上线销售。消费者可在云掌柜代销的合作平台上预订乙方所拥有的客房并完成支付流程。</p><p class="t12 mt5 mb5 green">二、代销合作</p><p class="t12 mt5 mb5">1、客房代销合作:双方采用底价模式,乙方在甲方代销服务页面设置的价格即为甲方结算给客栈的价格。甲方根据各分销渠道的费用率来制定实际对外销售价格,并承诺不裸卖。</p><p class="t12 mt5 mb5">2、客房代销收入:乙方在甲方代销服务页面所设置的底价。</p><p class="t12 mt5 mb5">3、客房代销最低房价保证:乙方承诺给予甲方最优价格保证,给予的底价应小于等于携程等 OTA 网络公开价扣除佣金之后的预付价格。</p><p class="t12 mt5 mb5">4、客房图片的授权使用:乙方承诺授权给甲方使用其客栈的房型图片,并保证图片的真实性和来源合法性。如若发生关于房型图片的侵权纠纷(包括但不限于侵权等纠纷),甲方将对此不承担任何法律责任。</p><p class="t12 mt5 mb5">5、自动落单确认方式:乙方同意在云掌柜代销平台上采用自动落单确认方式,具体模式如下:</p><p class="t12 mt5 mb5">1) 乙方承诺保证在云掌柜民宿管理软件上登记的房态房价房型等数据准确有效,只要乙方在云掌柜上登记的客房为可预订状态,甲方都有权利在云掌柜代销平台上直接进行销售, 无需与乙方进行沟通确认。</p><p class="t12 mt5 mb5">2) 只要客人在云掌柜代销平台上下单并完成支付,即视为乙方确定此订单,甲方也自动向客人确认订单,并在乙方云掌柜平台自动登记订单信息。乙方将承担按订单履行相关服务的义务和不能履行订单的赔付责任。</p><p class="t12 mt5 mb5">3) 订单确认之后,客人由于个人原因需要取消订单,需遵从甲方所合作渠道之取消规则。</p><p class="t12 mt5 mb5">6、推翻订单（满房/变价/装修等原因导致无法原单安排）处理方案：乙方同意一旦客人在云掌柜代销平台上完成预定支付流程但发生了推翻订单的情况，乙方将做如下的操作和赔付:</p><p class="t12 mt5 mb5">1) 免费升级房型:在客人同意的前提下,乙方应立即免费升级至更高级房型。在客人同意的前提下,乙方也可将客人安排至同区域、同级别或更高级别的客栈公寓,并承担客人原订单中全部房费及其他相关费用(包括但不限于后入住客栈与原客栈的房费差价、交通费等)。</p><p class="t12 mt5 mb5">2)赔付首晚房费:如客人不接受上述安排,则由此给客人及甲方造成的损失,乙方应负责赔偿。乙方应向客人如实说明不能兑现预订的具体原因并将上述情况及时通知甲方。除退还客人已付的相应房费外,乙方同意额外支付首晚的一晚房费给甲方用以赔付客人。</p><p class="t12 mt5 mb5">3) 甲方有权先行赔付:为保证客户体验,乙方授权甲方可以先行赔付,乙方承诺,在甲方赔付完成后 3 个工作日之内向甲方支付相应费用。乙方授权甲方可从乙方的客房销售款中扣除相应费用。</p><p class="t12 mt5 mb5">4) 如发生上述赔付情况,乙方拒不赔付,甲方可立即终止和乙方的代销合作;如乙方在一个季度内多次(三次以上)出现由房态、房价不准确导致的拒单,甲方有权提前终止与乙方的合作,且无需承担任何违约责任。</p><p class="t12 mt5 mb5 green">三、结算方式</p><p class="t12 mt5 mb5">云掌柜代销平台上的订单支付模式为客人在线预付。甲方将代乙方收取订单付款金额,并 在本月 15 日起的首个工作日结算上月所有离店订单房费到乙方指定账户。</p><p class="t12 mt5 mb5 green">四、违约责任</p><p class="t12 mt5 mb5">1、服务保障承诺:乙方须按照订单上的条款向客人提供服务。若乙方未按照订单提供服务 或因此导致客人纠纷的,应当按照让客人满意的原则改正并解决纠纷,所有费用由乙方承 担。若乙方怠于改正或解决纠纷,甲方有权自行解决,所有费用由乙方承担。</p><p class="t12 mt5 mb5">2、任何一方违反本协议的任何约定,均应向对方承担违约责任,赔偿由此给对方造成的合 理损失(包括但不限于律师费、诉讼费等)。</p><p class="t12 mt5 mb5 green">五、其他</p><p class="t12 mt5 mb5">1、乙方承诺及保证:</p><p class="t12 mt5 mb5">1.1 乙方须根据平台相关规则及要求向甲方保证具有合法、有效的经营资质并拥有相关证明, 包括但不限于营业执照、税务登记证、特种行业许可证、卫生许可证、消防合格安全证书 等。</p><p class="t12 mt5 mb5">1.2 乙方保证相关证明文件发生任何变更或更新时,及时通知甲方;若上述文件变更或更新 导致乙方不符合协议所规定的条件的,甲方有权单方全部或部分限制乙方经营,直至终止 本协议。</p><p class="t12 mt5 mb5">1.3 乙方对其相关证明文件或其他相应证明的真实性、合法性、准确性、有效性承担全部法律责任,若因乙方提交虚假、过期文件或未及时更新或通知证明文件导致纠纷或被相关国 家机关处罚的,由乙方独立承担全部法律责任,如因此造成云掌柜(包括“云掌柜”合作 方、代理人或职员)损失的,乙方应予以全额赔偿。</p><p class="t12 mt5 mb5">2、反腐败条款:一方保证不向另一方及与本合作有关的任何第三方的雇员或管理、工作人 员,直接或间接在账外暗中支付任何佣金、报酬或给予回扣。</p><p class="t12 mt5 mb5">3、承担保密义务:未经对方书面同意,任一方不得使用、向第三方披露或允许第三方使用 对方的任何保密、专有信息或商业秘密。本保密条款不因本协议的终止而失效。</p><p class="t12 mt5 mb5">4、不可抗力条款:如果不能履行本协议是由于一方所不能预见和控制的原因造成的,如战 争、罢工、自然灾害、恶劣天气、航空运输中断等,则不能履行本协议的一方可相应免责。</p><p class="t12 mt5 mb5">5、数据安全性保证:乙方需妥善保管其用户名、密码等身份认证信息,乙方在其云掌柜账 户下所有操作行为,均视为乙方行为或乙方授权行为。因乙方人员管理不善、账号密码保 管不善、输入信息错误,所导致的客房价格差错、结算、退款等纠纷,由乙方承担相应的 责任。</p><p class="t12 mt5 mb5">6、如双方就本协议内容或其执行发生任何争议,双方应进行友好协商。协商不成时,任何 一方均可向甲方所在地(北京)法院提起诉讼。</p><p class="t12 mt5 mb5">7、合同有效期:本协议合作期限为自合同签订之日起至 2017 年 12 月 31 日。合作期满前 30 日内,如合作各方均未向对方书面提出终止合作协议的,则本协议将自动顺延一年,依 此类推。</p><p class="t12 mt5 mb5">8、本协议自双方签字盖章(包括但不限于双方通过传真、电子邮件、系统平台确认签署等方式)之日起生效。本协议一式两份,双方各执一份,每份具有同等法律效力。通过传真方式签署的协议、电子邮件等方式确认签署的协议与纸质签署的协议具有同等法律效力。</p><p class="t12 mt5 mb5">9、本协议对乙方开办的分客栈具有法律效力,乙方的分客栈均依据本协议的相关约定享有相应的权利义务,乙方开办的分客栈如附件下表。乙方保证该等分客栈是乙方自行开设的分公司、分支机构或其控制的实体,并严格按照本协议的约定履行有关协议义务。</p><p class="t12 mt5 mb5" style="border-top:1px solid #ccc;padding-top:10px;">[以下无正文]</p><p class="t12 mt5 mb5">甲方:北京米天下科技股份有限公司</br>电子邮箱:kefu@miot.cn</br>联系电话:400-002-1566</br>签约时间: 年 月 日</br>盖章:</br>乙方:</br>授权协议签署人:</br>签署人身份证号码:</br>联系电话:</br>签约时间: 年 月 日</br>盖章:</br>乙方客栈列表(列表内客栈权利及义务等同于乙方主体):</p>','elong':'<p class="t14 mt10 mb10">关联艺龙后，可实现自动开关房、艺龙订单自动确认、订单信息直接录入到云掌柜，可减少操作成本，提高效率。</p>'
+'<p class="t14 mb10">关联艺龙，请知晓以下几点：</p>'
+'<p class="t14 mb10">1、如云掌柜上有充足剩余房量，将自动确认该订单，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、在云掌柜中录入订单，自动判断剩余房量并去艺龙开关房。</p>'
+'<p class="t14 mb10">3、限时抢购、预付、今夜特价、连住几晚优惠等均可关联；团购产品除外。</p>'
+'<p class="t14 mb10">4、艺龙卖价、担保规则、价格模式、佣金设置、房型信息等请继续在艺龙后台设置。</p>'
+'<p class="t14 mb10">5、艺龙不会获取到客栈在云掌柜上的任何数据。</p>','ctripbefore':'<p class="t14 mt10 mb10">关联携程后，可实现房量同步、房价同步、关联房型订单自动确认并落入云掌柜, 关联订单的入住/退房审核状态自动同步到携程。</p>'
+'<p class="t14 mb10">关联携程，需注意以下几点：</p>'
+'<p class="t14 mb10">1、与携程的双向直连服务，是云掌柜与携程子公司“入住通”进行提供，如果直连过程中出现什么问题，请客栈及时联系云掌柜，而不要联系携程。</p>'
+'<p class="t14 mb10">2、请确认所有对应房间的房型在ebooking上存在连续45天的房价，否则携程无法配置佣金完成上线。</p>'
+'<p class="t14 mb10">3、直连成功之后订单会自动确认并落入云掌柜，所以需要及时维护房态，保证房态准确。<span class="t14 red">因没有及时维护房态产生的所有赔付（订单确认后满房、客人到店无房）全部由客栈方自己承担。</span></p>'
+'<p class="t14 mb10">4、直连成功之后修改携程房价需要在云掌柜上修改，不要到ebooking上修改。<span class="t14 red">因没有在云掌柜上及时改价出现的低价误订一切损失由客栈方自己承担。</span></p>'
+'<p class="t14 mb10">5、每一个直连订单都要在云掌柜上及时办理入住及退房（未入住订单依然要到ebooking标记），以便完成订单审核。</p>','ctrip':'<p class="t14 mt10 mb10">关联携程后，可实现房量同步、关联房型订单自动确认并落入云掌柜。</p>'
+'<p class="t14 mb10">关联携程，需注意以下几点：</p>'
+'<p class="t14 mb10">1、与携程的直连服务，是云掌柜与入住通共同提供，如果直连过程中遇到任何疑问和问题，包括但不限于因各种问题产生的订单分歧，请及时联系云掌柜，云掌柜与入住通将全力协助解决。 </p>'
+'<p class="t14 mb10">2、直连后携程网站上的房价和房态仍旧在携程ebooking中维护；房量将来自于酒店在云掌柜中的维护数据。 </p>'
+'<p class="t14 mb10">3、直连后，如果云掌柜中有空房，且ebooking中该房型未关房，来自携程的订单将自动确认并自动落入云掌柜。 </p>'
+'<p class="t14 mb10">4、限时售卖、今夜甩卖、钟点房暂时不支持直连匹配；签约房无法实现自动开关房。</p>','qunarlink':'<p class="t14 mt10 mb10">关联去哪儿后，可实现房量同步、关联房型订单自动确认并落入云掌柜，关联订单的入住/退房审核状态自动同步到去哪儿。</p>'
+'<p class="t14 mb10">关联去哪儿，需注意以下几点：</p>'
+'<p class="t14 mb10">1、提供90天内的自动开关房功能以及和去哪儿房态对照功能。</p>'
+'<p class="t14 mb10">2、去哪儿“签约预留房”无法实现自动开关房。</p>','tujia':'<p class="t14 mb10">关联途家，请知晓以下几点：</p>'
+'<p class="t14 mb10">1、 与途家实现直连后，订单会自动确认并自动落入云掌柜；途家网站展示的房价和可售状态均来自于云掌柜。</p>'
+'<p class="t14 mb10">2、 与途家实现直连后，您在途家的订单将由云掌柜代为结算，结算周期为1个月， 请注意维护您在云掌柜的<a href="/Advanced/index" target="_blank" style="color: blue;text-decoration: underline">结算账号</a>信息。</p>'
+'<p class="t14 mb10">3、 与途家实现直连后，系统将帮助您在途家创建新的门店和房源。 如果您还未成为途家房东，请在此补充<a href="/Ota/info" target="_blank" style="color: blue;text-decoration: underline">房源创建所需的信息</a>。</p>'
+'<p class="t14 mb10">4、 如果您已经是途家房东，完成直连后，请注意将原来的房源处理下架。</p>','booking':'<p class="t14 mt10 mb5">1、 申请直连说明</p>'
+'<p class="t12 mb15"><a href="/Ota/downloadbooking">点击此处下载详细说明</a>，也可以联系您在云掌柜的客户经理获取指导。</p>'
+'<p class="t14 mt10 mb5">2、 申请直连Booking后台操作注意事项</p>'
+'<p class="t12 mb15">在Booking后台channel manager页面下，请选择供应商Yunzhanggui（ID 506）。</p>'
+'<p class="t14 mt10 mb5">3、 关联Booking实现的功能</p>'
+'<p class="t12 mb15">- 关联之前的订单，不论是原来的订单，还是后续产生的变更或取消，仍需要手工处理。<br>'
+'- 关联后，Booking订单的信用卡资料，需要您7日内到Booking后台获取。<br>'
+'- 关联后，如果您需要接收来自Booking的邮件，请联系您的Booking客户经理。</p>','agoda':'<p class="t14 mt10 mb10">关联Agoda后，可实现房量同步、房价同步、订单自动确认、订单信息直接录入到云掌柜。</p>'
+'<p class="t14 mb10">关联Agoda，请知晓以下几点：</p>'
+'<p class="t14 mb10">1、如云掌柜上有充足剩余房量，将自动确认该订单，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、在云掌柜中录入订单，自动判断剩余房量并去实时同步到Agoda。</p>'
+'<p class="t14 mb10">3、仅支持Agoda预付产品的直连。</p>','meituan':'<p class="t14 mb10">关联美团，请知晓以下几点：</p>'
+'<p class="t14 mb10">1、在云掌柜上录入订单，自动判断剩余房量并去美团后台开关房。</p>'
+'<p class="t14 mb10">2、提供90天内美团房态对照功能。</p>'
+'<p class="t14 mb10">3、仅支持美团预订产品的关联。</p>'
+'<p class="t14 mb10">4、如果您在关联之后修改了美团后台的密码，美团关联会自动断开。</p>','alitrip':'<p class="t14 mt10 mb10">关联阿里信用住后，可实现房量同步、订单自动确认、订单信息直接录入到云掌柜，可减少操作成本，提高效率。</p>'
+'<p class="t14 mb10">关联阿里信用住，请知晓以下几点：</p>'
+'<p class="t14 mb10">1、如云掌柜上有充足剩余房量，将自动确认该订单，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、在云掌柜中录入订单，自动判断剩余房量并去实时同步到阿里。</p>'
+'<p class="t14 mb10">3、关联阿里信用住后请及时对阿里信用住订单办理入住和退房。</p>'
+'<p class="t14 mb10">4、当前仅支持通过云掌柜签约的信用住酒店，<a href="/Ota/alitripapply" target="_blank">点击此处签约信用住</a>。</p>','airbnb':'<p class="t14 mb10">关联Airbnb ，请知晓以下几点：</p>'
+'<p class="t14 mb10">1、在云掌柜上录入订单，自动判断剩余房量并去Airbnb后台开关房。</p>'
+'<p class="t14 mb10">2、提供90天内Airbnb房态对照功能。</p>'
+'<p class="t14 mb10">3、仅支持Aribnb预订产品的关联。</p>'
+'<p class="t14 mb10">4、如果您在关联之后修改了Airbnb后台的密码，Airbnb关联会自动断开。</p>','zhenguo':'<p class="t14 mt10 mb10">关联榛果后，可实现房量同步、已确认订单信息直接录入到云掌柜。</p>'
+'<p class="t14 mb10">关联榛果，请知晓以下几点：</p>'
+'<p class="t14 mb10">1、订单的接单、拒单请到榛果后台完成。如云掌柜上有充足剩余房量，云掌柜会自动录入已确认的订单，并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、在云掌柜中录入订单，自动判断剩余房量并实时同步到榛果。</p>'
+'<p class="t14 mb10">3、直连后榛果网站上的房价仍旧在榛果后台维护；房态、房量将来自于云掌柜中的维护数据。</p>'
+'<p class="t14 mb10">4、直连后榛果后台仍可维护可售信息，具体可售信息以榛果后台为准。</p>','expedia':'<p class="t14 mb10"></p>'
+'<p class="t14 mb10"> 1、 申请直连说明</p>'
+'<p class="t12 mb10"><a href="/Ota/downloadexpedia" target="_blank">点击此处下载详细说明</a>，也可以联系您在云掌柜的客户经理获取指导。</p>'
+'<p class="t14 mb10">2、 申请直连Expedia后台操作注意事项\n</p>'
+'<p class="t12 mb10">在Expedia后台 Partner Central页面下，请选择供应商Yunzhanggui。</p>'
+'<p class="t14 mb10">3、 关联Expedia实现的功能</p>'
+'<p class="t12 mb10">- 关联之前的订单，不论是原来的订单，还是后续产生的变更或取消，仍需要手工处理。</p>'
+'<p class="t12 mb10">- 关联后，请及时维护云掌柜房态与房价，以免造成到店无房以及底价误订的情况。</p>','jihe':'<p class="t14 mb10">几何民宿与云掌柜关联，请知晓以下几点：</p>'
+'<p class="t14 mb10"> 1、 如云掌柜上有充足剩余房量，几何民宿推送给我们的订单将被自动确认，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、 仅支持几何民宿获取云掌柜上客栈上架房型房量的数据。</p>'
+'<p class="t14 mb10">3、 云掌柜获取不到客栈在几何民宿上的任何数据。</p>','qmango':'<p class="t14 mb10">青芒果与云掌柜关联，请知晓以下几点：</p>'
+'<p class="t14 mb10"> 1、 如云掌柜上有充足剩余房量，青芒果推送给我们的订单将被自动确认，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、 仅支持青芒果获取云掌柜上客栈上架房型房量的数据。</p>'
+'<p class="t14 mb10">3、 云掌柜获取不到客栈在青芒果上的任何数据。</p>','xiaozhu':'<p class="t14 mb10">关联小猪短租，请知晓以下几点：</p>'
+'<p class="t14 mb10">1、在云掌柜中录入订单，自动判断剩余房量并去实时同步到小猪短租。</p>'
+'<p class="t14 mb10">2、提供60天内小猪短租的房态对照功能。</p>'
+'<p class="t14 mb10">3、仅支持小猪短租预定产品的关联。</p>','weila':'<p class="t14 mb10">维拉度假与云掌柜关联，请知晓以下几点：</p>'
+'<p class="t14 mb10"> 1、 如云掌柜上有充足剩余房量，维拉度假推送给我们的订单将被自动确认，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、 仅支持维拉度假获取云掌柜上客栈上架房型房量的数据。</p>'
+'<p class="t14 mb10">3、 云掌柜获取不到客栈在维拉度假上的任何数据。</p>','msk':'<p class="t14 mb10">民宿客与云掌柜关联，请知晓以下几点：</p>'
+'<p class="t14 mb10"> 1、 如云掌柜上有充足剩余房量，民宿客推送给我们的订单将被自动确认，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、 仅支持民宿客获取云掌柜上客栈上架房型房量的数据。</p>'
+'<p class="t14 mb10">3、 云掌柜获取不到客栈在民宿客上的任何数据。</p>','zhisu':'<p class="t14 mb10">知宿与云掌柜关联，请知晓以下几点：</p>'
+'<p class="t14 mb10"> 1、 如云掌柜上有充足剩余房量，知宿推送给我们的订单将被自动确认，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、 仅支持知宿获取云掌柜上客栈上架房型房量的数据。</p>'
+'<p class="t14 mb10">3、 云掌柜获取不到客栈在知宿上的任何数据。</p>','jsyx':'<p class="t14 mb10">借宿严选与云掌柜关联，请知晓以下几点：</p>'
+'<p class="t14 mb10"> 1、 如云掌柜上有充足剩余房量，借宿严选推送给我们的订单将被自动确认，录入到云掌柜并自动分房，订单信息可自由修改。</p>'
+'<p class="t14 mb10">2、 仅支持借宿严选获取云掌柜上客栈上架房型房量的数据。</p>'
+'<p class="t14 mb10">3、 云掌柜获取不到客栈在借宿严选上的任何数据。</p>',},rules_footer:{'yzgdx':'下一步，设置价格','elong':'继续','ctrip':'继续','qunarlink':'下一步，开始关联去哪儿','tujia':'下一步，开始关联途家','booking':'下一步，开始关联Booking','agoda':'下一步，开始关联Agoda','meituan':'下一步，开始关联美团','alitrip':'继续',},orderpay:null,chargesetting:{},init:function(){this.initDOM();this.initEvent();},initDOM:function(){this.context.otalist=$('#otalist');this.context.otalist1=$('#otalist1');this.context.rulestpl=$("#rulestpl");this.orderpay=orderpay;},initEvent:function(){this.context.otalist.bind('click',this.otalist_click.toEventHandler(this));this.context.otalist1.bind('click',this.otalist_click.toEventHandler(this));this.context.rulestpl.bind("click",this.rulestpl_click.toEventHandler(this));},otherinntoggle:function(){var target=this.context.payform.find('ul[tag=innlist]').find('div[tag=inn]');var index=1;target.each(function(){if(index>5){$(this).toggle();}
index++;});},canclerule_change:function(e){var ele=M.EventEle(e);if(ele.val()==3){this.context.rulestpl.find('div[tag=canclerule]').find('div[tag=ruletip]').show();}else{this.context.rulestpl.find('div[tag=canclerule]').find('div[tag=ruletip]').hide();}},otalist_click:function(e)
{var ele=M.EventEle(e);var t=ele.attr("tag");if(t=='buy'){this.context.rulestpl.children("div[tag=btn]").show();this.orderpay.ota_buy(ele);}else if(t=="tipsmsg"){this.context.rulestpl.children("div[tag=btn]").hide();this.ota_apply(ele);}},ota_apply:function(ele){var otacode=ele.parents("li").attr("ota");if(M.isEmpty(this.rules_title[otacode])){alert('渠道不存在');return;}
this.otacode=otacode;this.context.rulestpl.find('h3').html(this.rules_title[otacode]);this.context.rulestpl.find('div[tag=content]').html(this.rules_content[otacode]);this.context.rulestpl.find('a[tag=noopen]').html(this.rules_footer[otacode]);if(otacode=='yzgdx'){this.context.rulestpl.find('div[tag=canclerule]').show();this.context.rulestpl.find('div[tag=canclerule]').find('select').children('option:eq(0)').attr('selected','selected');this.context.rulestpl.find('div[tag=ruletip]').hide();}else{this.context.rulestpl.find('div[tag=canclerule]').hide();}
M.Popup(this.context.rulestpl,{"hideclass":"bootbox modal fade","showclass":"bootbox modal fade in"},function(){}.toEventHandler(this));return;},rulestpl_click:function(e){var ele=M.EventEle(e);var t=ele.attr('tag');switch(t){case'agreemsg':this.agreemsg(ele);break;case'open':this.pass(ele);break;case'noopen':return;case'closebtn':this.rulesTplCloseBtn();return;break;}},rulesTplCloseBtn:function(){var divBtn=this.context.rulestpl.children('div[tag=btn]');divBtn.find('input[tag=agreemsg]').removeAttr('checked');divBtn.find('a[tag=open]').attr('tag','noopen');this.otacode='';},noopen:function(){alert("请先同意关联"+this.ota_type[this.otacode]+"免责条款");},agreemsg:function(ele){var value=ele.val();if(value==1){ele.val("0");ele.parents('div[tag=btn]').find('a[tag=open]').attr('tag','noopen').removeClass('btn-primary').addClass('btn-waiting');}else{ele.val("1");ele.parents('div[tag=btn]').find('a[tag=noopen]').attr('tag','open').removeClass('btn-waiting').addClass('btn-primary');}},pass:function(ele){var agreestatus=this.context.rulestpl.children().find("input[name=agreebtn]").val();var code=this.otacode;if(agreestatus==0){this.noopen();return;}
if(code=='yzgdx'){M._getjson("/Ota/applyyzg",{},this.applyyzg_finished.toEventHandler(this),null,true);}else{M._getjson("/Ota/applyOpen",{"act":"otaapply","otacode":code},this.pass_finished.toEventHandler(this),null,true);}},applyyzg_finished:function(d){if(d.status=="success"){window.location.href='/Ota/yzgdx';}else{alert(d.msg);}},pass_finished:function(d){if(d.status=="success"){var otacode=d.req.otacode;if(otacode=='ctrip'){window.location.href='/Ota/'+'ctripall';}
else{window.location.href='/Ota/'+otacode;}}else{alert(d.msg);}},_closepopup:function()
{M.CloseLast();},destroy:function(){}});M.ready(function(){var otaOther=new M.Page.OtaOtherPage();return otaOther;});