M.Page.ReportpointsPage=M.createClass();M.extend(M.Page.ReportpointsPage.prototype,{context:{},init:function(){this.initDOM();this.initEvent();this.initData();},initDOM:function(){this.context.innlist=$("#innlist");this.context.monthlist=$("#monthlist");this.context.tips=$("#tips");this.context.pointstip=$("#pointstip");this.context.pagelist=$("#pagelist");this.context.pagelist2=$("#pagelist2");this.context.earnedlist=$("#earnedlist");this.context.deductlist=$("#deductlist");this.context.pointsdetail=$('#pointsdetail');this.context.body=$("body");},initEvent:function(){this.context.monthlist.bind('click',this.monthlist_click.toEventHandler(this));this.context.body.bind('click',this.body_click.toEventHandler(this));this.context.tips.bind('click',this.tips_click.toEventHandler(this));this.context.pagelist.bind('click',this.pagelist_click.toEventHandler(this));this.context.pagelist2.bind('click',this.pages_click.toEventHandler(this));},initData:function(){M.DropdownList(this.context.innlist,this.changeinnlist.toEventHandler(this),{});},tips_click:function(){M.Popup(this.context.pointstip,{"hideclass":"modal sm fade","showclass":"modal sm fade in"},function(){}.toEventHandler(this));},monthlist_click:function(e){var ele=M.EventEle(e);var month=ele.attr('month');window.location.href='/Report/points?month='+month;},changeinnlist:function(ele){var innid=ele.attr("value");window.location.href='/Report/points?innid='+innid;},body_click:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");var innlength=ele.parents("div[id=innlist]").length;if(innlength==0){this.context.innlist.children("div").hide();}},pagelist_click:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");switch(tag){case'page':this.gotopage(ele,'earned');break;}},pages_click:function(e){var ele=M.EventEle(e);var tag=ele.attr("tag");switch(tag){case'page':this.gotopage(ele,'deduct');break;}},gotopage:function(ele,type){var p=ele.attr("p");if(M.isEmpty(p))
return;var innid=this.context.innlist.children("span").attr("value");var month=this.context.monthlist.find("li.on").attr('month');var data={"innid":innid,'page':p,'month':month};if(type=='earned'){M._getjson("/Points/getEarnedPointsDeatils",data,this.getearnedlist_finished.toEventHandler(this));}
if(type=='deduct'){M._getjson("/Points/getDeductPointsDeatils",data,this.getdeductlist_finished.toEventHandler(this));}},getearnedlist_finished:function(d){if(d.status=="success"){var list=d.data.list;var pages=d.data.pages;var month=d.data.month;var html='';for(var i=0;i<list.length;i++){var item=list[i];html+="<tr><td>"+item.cdate+"</td><td>"+item.normalpoints+"</td><td>"+item.otherpoints+"</td><td>"+item.todaypoints+"</td></tr>";}
html+="<tr><td class='bg-total'>总计</td></td><td class='bg-total'></td><td class='bg-total'></td><td class='bg-total'>"+d.data.total+"</td></tr>";this.context.earnedlist.children("tbody").html(html);var page_html=this._handlepages(pages);this.context.pagelist.html(page_html);if(month.month=='month'){var month_html='<li month="month" class="first on"><a href="#?" month="month">本月</a></li>';if(month.prevmonthstatus==1){month_html+='<li month="prevmonth" class="first"><a href="#?" month="prevmonth">上月</a></li>'}}else{var month_html='<li month="month" class="first"><a href="#?" month="month">本月</a></li><li month="prevmonth" class="first on"><a href="#?" month="prevmonth">上月</a></li>'}
this.context.monthlist.html(month_html);}else{M.error(d.msg);}},getdeductlist_finished:function(d){if(d.status=="success"){var list=d.data.list;var pages=d.data.pages;var html='';for(var i=0;i<list.length;i++){var item=list[i];html+="<tr><td>"+item.createon+"</td><td>"+item.remark+"</td><td>"+item.points+"</td></tr>";}
this.context.deductlist.children("tbody").html(html);this.context.pointsdetail.find("span[tag=deducttotal]>strong").text(d.data.total);var page_html=this._handlepages(pages);this.context.pagelist2.html(page_html);}else{M.error(d.msg);}},_handlepages:function(pages){var list=pages.pagelist;if(list.length==0)
return;var nextpage=pages.nextpage;var pageindex=pages.pageindex;var maxpage=pages.maxpage;var prepage=pages.prepage;var html='<li><a p="'+prepage+'" tag="page" href="#">&laquo;</a></li>';for(var i=0;i<list.length;i++){var p=list[i];if(p.code==pageindex){html+='<li class="active"><a href="#?" title="">'+p.name+'</a></li>';}else{html+=' <li><a href="#?" tag="page" p="'+p.code+'" title="">'+p.name+'</a></li>'}}
if(maxpage>5){if(maxpage-pageindex>2){html+='<li><a href="#?">...</a></li>';html+='<li><a href="#?" tag="page" p="'+maxpage+'">'+maxpage+'</a></li>';}}
html+='<li><a href="#" tag="page" p="'+nextpage+'">&raquo;</a></li>';return html;},_closepopup:function()
{M.ClosePopup();},destroy:function(){}});M.ready(function(){var points=new M.Page.ReportpointsPage();return points;});